version: "3"
services:

  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - "./tempo/tempo.yaml:/etc/tempo.yaml"
      - "./tempo/tempo-data:/tmp/tempo"
    ports:
      - "3200:3200"   # tempo
    #  - "4317:4317"  # otlp grpc
    networks:
      - otelnetwork
      
  k6-tracing:
    image: ghcr.io/grafana/xk6-client-tracing:v0.0.2
    environment:
      - ENDPOINT=otel-collector:4317
    restart: always
    depends_on:
      - otel-collector
    networks:
      - otelnetwork
      
      
  otel-collector:
    image: otel/opentelemetry-collector:0.92.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - "./otel/otel-collector.yaml:/etc/otel-collector.yaml"
    ports:
      - "4317:4317"  # otlp grpc
    networks:
      - otelnetwork
      
  grafana:
    image: grafana/grafana:10.2.2
    volumes:
      - "./grafana/grafana.ini:/etc/grafana.ini"
      - "./grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml"
      - "./grafana/data:/var/lib/grafana"
    environment:
    #  - GF_AUTH_ANONYMOUS_ENABLED=true
    #  - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    #  - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
      - GF_PATHS_DATA=/var/lib/grafana/data
      - GF_PATHS_LOGS=/var/lib/grafana/logs
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/var/lib/grafana/provisioning
      - GF_DATABASE_TYPE=sqlite3
    ports:
      - "3000:3000"
    networks:
      - otelnetwork
      
networks:
  otelnetwork:
    external: true
  
